Домашка, 7 пара Кузьмич Александр, 9 пунктов 🎉
kontur-web-courses/react-ts pull request #1
Opened 2021-02-27 13:04 UTC by KuzmichAlexander

2021-03-02 09:15 UTC, nulladdict requested changes
Первая часть сделана хорошо, есть лишь небольшие замечания, во второй части (8-9) слишком сильно перемудрили и стало непонятно и нечитаемо

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/App.tsx
> +    curr: { city: "", name: "", surname: "" }
Можно избавиться от копипасты если вынести дефолтное состояние в константу

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/App.tsx
> +  onChangeName: (e: string) => void; //попался в ловушку ивентов React.BaseSyntheticEvent<HTMLInputElement>
О какой ловушке ивентов здесь идет речь?

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/App.tsx
> +  onChangeSurname: (e: string) => void; //а если мне нужно не только свойство e.target.value?
`Input` из библиотеки поддерживает не только `onValueChange`, но и `onChange`, в который приходит настоящий ивент

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/App.tsx
> +          <Input value={surname} onValueChange={(e) => onChangeSurname(e)} placeholder="Введите фамилию пользователя" /></label>
Для чего здесь ещё одна обёртка в `onValueChange`, почему бы не передавать `onChangeSurname` напрямую?

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/App.tsx
> +  onChangeSurname: (e: string) => void; //а если мне нужно не только свойство e.target.value?
Но эту задачу можно полностью решить используя только `onValueChange`

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/CustomModal.tsx
> +    const diffArray: Array<React.FC> = [];
Здесь должен быть не `React.FC`, а `React.ReactNode`, первый тип для описания функций-конструкторов, второй — для элементов, которые получаются после рендера и которые можно вставлять в разметку

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/CustomModal.tsx
> +    Object.keys(prev).forEach((key, index) => {
`Object.keys(obj)` возвращает `string[]`, а не `keyof typeof obj`, поэтому тут теряется информация о типах и TS ниже ругается

Починить можно кастанув `key` при использовании к правильному типу, например так:
`const k = key as keyof saveDataType`

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/CustomModal.tsx
> +        diffArray.push(<Difference key={key} prop={propArray[index]} prevName={prev[key]} currName={curr[key]} />);
В этой строчке `prevName` и `currName` ожидают строчку, но судя по типам туда вполне может прийти `undefined`, но этого не видно из-за двух `@ts-ignore` сверху.

Поэтому когда что-то изменилось с отсутствия значения на наличие значение выводится что-то странное. Правильнее будет выводить, что раньше была какая-нибудь специальная строка, например `**ничего**` как в примере решения

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/CustomModal.tsx
> +      return null;
Почему бы сразу здесь не возвращать `"Данные не изменены."`, чтобы не добавлять ещё одно условие снизу?

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/CustomModal.tsx
> +    {prop}: было: {prevName}, стало: {currName}
Кажется здесь потерян случай, когда было или стало ничего

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/style.css
> +.custom-input {
Этих стилей явно не достаточно чтобы сделать компонент похожим на то, каким его дает библиотека контролов.

Если взялись реализовывать свои контролы, то делайте все согласно описанию того, как они должны выглядеть и работать: https://guides.kontur.ru/components/input/

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/style.css
> +    outline: none;
Не надо так делать, полностью потерялось состояние фокуса

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/App8-9.tsx
> +        },
Копипаста, нужно вынести в отдельную переменную

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/App8-9.tsx
> +      }
Нет никаких причин хранить это внутри `state`. Если это было сделано, чтобы избежать излишнего дублирования, то получилось неудачно, потому что дублирование перенеслось в state, в месте, где всё рисуется стало ничего не понятно

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/App8-9.tsx
> +    const discr = e.target.id;
В принципе, не плохой подход, проще было бы например делать как в решении, создавать в момент рендера отдельную функцию для каждого инпута, которая уже будет знать куда писать

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/App8-9.tsx
> +      inputs: {
В принципе так присваивать ок, но тут какая-то слишком большая вложенность и от этого все очень страшно выглядит

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/App8-9.tsx
> +    let emptyInputsFlag = false;
Для проверки можно было воспользоваться стандартным интерфейсом для считывания значения формы:
[`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData)

Да и на самом деле можно было совсем не хранить значения инпутов в `state`, а считывать их только в момент сабмита формы с помощью `new FormData(e.target)`

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/CustomInput.tsx
> +        <select className={"custom-input"} value={value} onChange={onChangeInput} id={id} placeholder={placeholder}>
Не нужно было изобретать велосипеды и писать свои инпуты, проще было воспользоваться инпутами из библиотеки контролов

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/Form.tsx
> +        {setInputs()}
Вместо того, чтобы писать логику отрисовку инпутов, проще было принять в качестве детей и использовать здесь `{children}`

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/consts.ts
> +export const cities: Array<string> = ["Выбирите город", "Липецк", "Троицк", "Новокузнецк", "Челябинск", "Владивосток"];
`"Выбирите город"` не должен быть отдельным значением в `select`-е, иначе пользователь сможет его выбрать в качестве валидного значения и сохранить

2021-03-02 09:15 UTC, nulladdict commented on userProfile/src/task8-9/consts.ts
> +export const maritalStatuses: Array<string> = ["Семейное положение", "Замужем", "Не замужем", "Пишу код по ночам"];
`"Семейное положение"` тоже не место среди значений, по той же причине что и в случае с городом

2021-03-02 11:40 UTC, KuzmichAlexander commented on userProfile/src/App.tsx
> +  onChangeSurname: (e: string) => void; //а если мне нужно не только свойство e.target.value?
WebStorm упорно сопротивлялся на onChange, и я решил что его нет (и в документации про это тоже не было сказано)

2021-03-02 11:41 UTC, KuzmichAlexander commented on userProfile/src/App.tsx
> +  onChangeName: (e: string) => void; //попался в ловушку ивентов React.BaseSyntheticEvent<HTMLInputElement>
Забыл коммент подтереть, для себя оставил чтобы почитать позже про типизацию ивентов

2021-03-02 11:42 UTC, KuzmichAlexander commented on userProfile/src/CustomModal.tsx
> +    const diffArray: Array<React.FC> = [];
Понял, до этого не знал об этом

2021-03-02 11:48 UTC, KuzmichAlexander commented on userProfile/src/task8-9/consts.ts
> +export const cities: Array<string> = ["Выбирите город", "Липецк", "Троицк", "Новокузнецк", "Челябинск", "Владивосток"];
Не сможет, т.к. value у это опции `undefined` и форма не сабмитнется, это же и с семейным положение (суть 8 пункта)

2021-03-02 11:52 UTC, KuzmichAlexander commented on userProfile/src/CustomModal.tsx
> +      return null;
Справедливо

2021-03-02 18:07 UTC, nulladdict commented on userProfile/src/task8-9/App8-9.tsx
> +    let emptyInputsFlag = false;
upd: `<Select />` не прокидывает name и value внутрь инпута (там сейчас вообще внутри button), но если хочется не хранить состояние можно сделать вот такую обертку:

```jsx
const UncontrolledSelect = ({ defaultValue, name }) => {
  const [value, setValue] = useState(defaultValue)
  return <>
    <Select value={value} onValueChange={setValue} />
    <input type="hidden" value={value} name={name} />
  </>
}
```

Такая штуковина позволит собрать значения всех полей формы при вызова `new FormData(e.target)`

2021-03-03 04:06 UTC, KuzmichAlexander commented on userProfile/src/task8-9/App8-9.tsx
> +    let emptyInputsFlag = false;
Понял, принял 👍

2021-03-10 05:20 UTC, closed without merging