Обновление курса
kontur-web-courses/react-ts pull request #39
Opened 2023-05-15 07:46 UTC by Nevenq

* Перевел оставшиеся две таски на тайпскрипт
* Обновил все зависимости
* Немного обновил слайды

2023-05-24 19:37 UTC, disturm commented
Может быть скриншоты переделать? Когда делаешь скриншот есть смысл уменьшать размер окна браузера, чтобы весь контент влезал на меньшее пространство. Тогда после вставки в презентацию или еще куда-то такая картинка на слайде займет столько же места, но все элементы будут там крупнее.

2023-05-24 19:45 UTC, disturm approved these changes

2023-05-24 19:45 UTC, disturm commented on tasks/src/8.FormRow/solved/index.tsx
> +  // forward.displayName = FormRow.displayName;
Какой смысл это оставлять? Надо либо написать так, как надо делать. Либо убрать полностью.

2023-05-24 19:45 UTC, disturm commented on userProfile/package.json
> +    "start": "webpack serve --mode development --port=8081"
Точно ли это нужно? У меня есть гипотеза, что одновременно запускать оба приложения надо только преподавателю. А в случае обучения удобно, что порт всегда один и тот же. Что подсказывает твоя практика?
Если все же порт другой, то надо  забыть его попиарить в презентации! А там я вроде не увидел.

2023-07-03 08:44 UTC, disturm requested changes
Предложил пару идей, которые стоит обдумать и применить решение ко всему коду.
В целом, правильное и актуальное изменение. Спасибо за исправление опечаток ))

2023-07-03 08:44 UTC, disturm commented on index.html
> +return (
Что случилось с отступами?

2023-07-03 08:44 UTC, disturm commented on tasks/src/8.FormRow/index.tsx
> +  const [opened, changeOpened] = React.useState(false);
Обычно используется не changeOpened, а setOpened:
https://legacy.reactjs.org/docs/hooks-state.html

Не настаиваю, что тебе надо использовать change в свой практике, но курс должен быть про общепринятые названия. Если же уже повсеместно используется change, то тогда и тут надо оставить его.

Это глобальный комментарий, относящийся к этому и другим местам.

2023-07-03 08:44 UTC, disturm commented on tasks/src/8.FormRow/index.tsx
> +      <FormRow {...props} forwardedRef={ref} />
Если GitHub не обманывает, то здесь нужен отступ

2023-07-03 08:44 UTC, disturm commented on tasks/src/8.FormRow/solved/index.tsx
> +  const renderOpenButton = () => {
Вот тут у меня есть вопрос к практикующим фронтендерам. Как правильно: объявлять все такие функции внутри главной функции компонента, либо вытащить их вовне и передавать все необходимое через параметры?

Почему есть вопрос. Возможно, определение всех функций при каждом рендере -- это так себе идея и лучше один раз их опредеелить вовне и переиспользовать. Также вариант, когда все свалено в одну функцию выглядит недостаточно декомпозированным. С другой стороны, возможно влияние на производительность минимально, а код так писать удобнее.

В любом случае, хочется по возможности показывать хорошие актуальные практики в этом курсе. Так что рекомендую поспрашивать коллег, если ты еще этого не сделал.

2023-07-05 05:03 UTC, Nevenq commented on tasks/src/8.FormRow/solved/index.tsx
> +  const renderOpenButton = () => {
На самом деле ни разу не встречал решения, чтобы выносили такие функции за компонент. С точки зрения производительности пересоздание функции влияние функции минимально, но выносить хендлеры действительно не очень удобно. 
Вот на чем действительно это может сказаться это на лишних перерендерах, но и эта проблема решается при помощи `React.useCallback`. Но переусердствовать с ним тоже не стоит, вот, что говорится в [документации](https://react.dev/reference/react/useCallback#should-you-add-usecallback-everywhere).

> If your app is like this site, and most interactions are coarse (like replacing a page or an entire section), memoization is usually unnecessary.
То-есть для обычных веб приложений стоит прибегнуть к мемоизации только если возникают проблемы с производительностью.

Узнав у коллег и посмотрев репозитории, увидел, что аналогично думаю и другие фронтендеры. В проектах множество хендлеров и так называемых рендер функций, которые определены внутри функции компонента.

2023-07-06 05:44 UTC, merged