Чумерина (4 пара)
kontur-web-courses/react-ts pull request #7
Opened 2021-03-03 13:37 UTC by MariaChumerina

2021-03-07 06:55 UTC, Ollisteka requested changes
Давай уберём циклическую зависимость между `Main`, `ModalComponent` и `Form`? А всё остальное некритично, можешь поправить, а можешь просто учесть на будущее :)

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/index.tsx
> +    <>
Если внутри пустого тега только один ребёнок, то его лучше вообще не писать. Как минимум, на один уровень вложенности меньше будет

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/data/cities.js
> +export const cities = [
Здорово, что убрала эти данные отдельно! 👍

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/Main.tsx
> +export interface DiffFormState {
Я бы здесь ещё дальше с типизацией пошла. Сейчас в компоненте ModalComponent есть неочевидная надежда на то, что в пропсах действительно будут поля name, surname и city. Но можно взять енам из соседнего файла, и затипизировать ещё надёжнее:

```
export type DiffFormState = {
    [key in FormDataEnum]: {
        prevValue: string;
        value: string;
        hasChanged: boolean;
    };
};
```

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/Main.tsx
> +import { ModalComponent } from './ModalComponent';
Сейчас Main зависит от ModalComponent и от Form, а они -- от Main. Нехорошая циклическая зависимость получилась, которая может ко всяким неприятным штукам привести.
Раз и форма, и модалка, экспортируют только тип, то лучше этот тип в отдельный файлик рядом сложить, чтобы все три компонента обращались к нему

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/Main.tsx
> +            <Form saveForm={diffState => onSaveForm(diffState)} />
Здесь и в следующей строчке можно не создавать новую стрелочную функцию, а саму функцию передавать: `saveForm={onSaveForm}`, раз они никаких дополнительных параметров не принимают

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/ModalComponent.tsx
> +export const ModalComponent: React.FC<ModalComponentProps> = ({ closeModal, diffState }) => {
Можно избавиться от постоянного упоминания diffState ниже, деструктурировав его вот так: `diffState: { name, surname, city }`. И тогда блоки с изменённми данными совсем похожими начинают выглядеть, аж хочется их в свой собственный компонент вынести, чтобы не дублировать вот этот кусок:
```
hasChanged && <p>{field}: было {prevValue}, стало {value}</p>
```

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/Form.tsx
> +        prevValue: '',
Этот объект можно в какой-нибудь `defaultFieldState` вынести, и переиспользовать для всех полкй

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/Form.tsx
> +        <>
Пустой тег можно опустить, раз внутри только один ребёнок

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/Form.tsx
> +                    <Button use="primary" onClick={() => onSave()}>
Более правильным решением с точки зрения web-доступности было бы указать этой кнопке `type="submit"` и положить `onSave` в пропс `onSubmit` у формы. Тогда как минимум заработает отправка формы по Enter из любого инпута, и не надо будет табаться до самой кнопки "Сохранить")

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/Form.tsx
> +        for (const key in diffState) {
Здесь и в 64 строчке можно итерироваться по `FormDataEnum` -- станет и очевиднее, и короче

2021-03-07 06:55 UTC, Ollisteka commented on userProfile/src/components/Form.tsx
> +            diffState[key as diffStateKeyType].value = name;
Эта строчка выглядит лишней :) Как вариант, можно было бы хранить поля формы не в отдельных переменных, а в одном объекте `{ name: '', surname: '', city: '' }`, присваивать нужное поле в этой строке, а строчки 60-62 выпилить.

А вообще, можно было бы совсем не заводить реактивный стейт под поля формы, а использовать средства, которые нам DOM предоставляет: FormData + либо реактивная ссылка на форму, или просто форма из event.target, если использовать onSubmit на форму. Главное, не забыть пропс `name` всем инпутам добавить

2021-03-11 09:06 UTC, MariaChumerina commented on userProfile/src/components/Main.tsx
> +import { ModalComponent } from './ModalComponent';
Прочитала сначала верхний комментарий и неправильно поняв, исправила зависимость тем, что удалила Main компонент и перенесла всю логику из него в Form:(

2021-03-11 15:19 UTC, Ollisteka commented on userProfile/src/components/Form.tsx
> +import {ModalComponent} from "./ModalComponent";
Отступы потерялись и кавычки не те))

2021-03-11 15:19 UTC, Ollisteka commented on userProfile/src/index.tsx
> +import {Form} from "./components/Form";
И тут преттиером бы пройтись)

2021-03-11 15:19 UTC, Ollisteka commented on userProfile/src/components/Main.tsx
> +import { ModalComponent } from './ModalComponent';
Сейчас всё равно остались "двунаправленные" импорты:
`import {ModalComponent} from "./ModalComponent";` в Form
и 
`import { DiffFormState } from './Form';` в ModalComponent

Два компонента ссылаются друг на друга, и это нехорошо, надо, чтобы стрелочки связей были однонаправленные

То есть не так:
`ModalComponent <-> Form`
А вот так:
`ModalComponent -> commonTypes.ts <- Form`

А в commonTypes.ts будет лежать как раз `DiffFormState`

2021-03-11 15:21 UTC, Ollisteka commented on userProfile/src/components/Main.tsx
> +import { ModalComponent } from './ModalComponent';
И мне как раз понравилось, что у тебя был отдельный Main, а форма и модалка получились практически независимыми. То есть можно было бы на другой какой нибудь страничке спокойно использовать форму без модалки) Но в рамках этой задачи в целом непринципиально)

2021-03-11 16:42 UTC, MariaChumerina commented on userProfile/src/components/Main.tsx
> +import { ModalComponent } from './ModalComponent';
аа, всё оказалось намного проще, чем я думала, исправила, спасибо!
а Main, в принципе, поэтому и сделала, чтобы всё было не зависимым)

2021-03-13 05:09 UTC, closed without merging